/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cardealertrydesign;

import cardealertrydesign.DBmanager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Jericho Mico
 */
public class CarJframe extends javax.swing.JFrame {

    public CarJframe() {
        initComponents();
        
        DBmanager Db = new DBmanager();
        Db.getConnection();
        
        customerManagement Customer = new customerManagement("", "", "", "", "");
        Customer.fillTableCustomer(customerTable);
        
        vehicleManagement Vehicle = new vehicleManagement("", "", null, 0.0, null);
        Vehicle.fillTableVehicle(vehicleTable);
        
        salesManagement Sales = new salesManagement("","",null, null);
        Sales.fillTableSales(salesTable);
        MainPanel.removeAll();
        MainPanel.add(HomePanel);
        HomePanel.repaint();
        HomePanel.revalidate();
        

    }
    
    customerManagement Customer = new customerManagement("", "", "", "", "");
    vehicleManagement Vehicle = new vehicleManagement("", "", null, 0.0, null);
    salesManagement Sales = new salesManagement("","",null, null);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addCustomerMain = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        recordSales = new javax.swing.JLabel();
        viewSalesMain = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        ViewSalesPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        salesTable = new javax.swing.JTable();
        txtsearch3 = new javax.swing.JTextField();
        searchsaleButton = new javax.swing.JButton();
        clearSearch = new javax.swing.JButton();
        salesID = new javax.swing.JTextField();
        SF1 = new javax.swing.JTextField();
        SF2 = new javax.swing.JTextField();
        SF3 = new javax.swing.JTextField();
        deleteSales = new javax.swing.JButton();
        SF4 = new javax.swing.JTextField();
        SF5 = new javax.swing.JTextField();
        viewVehiclePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        vehicleTable = new javax.swing.JTable();
        txtsearch2 = new javax.swing.JTextField();
        vehicleSearch = new javax.swing.JButton();
        VF1 = new javax.swing.JTextField();
        VF2 = new javax.swing.JTextField();
        VF3 = new javax.swing.JTextField();
        VF4 = new javax.swing.JTextField();
        VF5 = new javax.swing.JTextField();
        clearSearch2 = new javax.swing.JButton();
        updateVehicle = new javax.swing.JButton();
        deleteVehicle = new javax.swing.JButton();
        salesRecord = new javax.swing.JPanel();
        SidF = new javax.swing.JTextField();
        SpurchaseF = new javax.swing.JTextField();
        ScidF = new javax.swing.JTextField();
        SvidF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        HomePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        addCustomerPanel = new javax.swing.JPanel();
        CphoneF = new javax.swing.JTextField();
        CaddressF = new javax.swing.JTextField();
        CidF = new javax.swing.JTextField();
        CnameF = new javax.swing.JTextField();
        CemailF = new javax.swing.JTextField();
        CnameL = new javax.swing.JLabel();
        CemailL = new javax.swing.JLabel();
        CphoneL = new javax.swing.JLabel();
        CaddressL = new javax.swing.JLabel();
        CidL = new javax.swing.JLabel();
        ClearCustomer = new javax.swing.JButton();
        addCustomerB = new javax.swing.JButton();
        viewCustomers = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        txtsearch = new javax.swing.JTextField();
        searchCbutton = new javax.swing.JButton();
        CF7 = new javax.swing.JTextField();
        CF8 = new javax.swing.JTextField();
        CF9 = new javax.swing.JTextField();
        CF10 = new javax.swing.JTextField();
        customerID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        customerUpdateB = new javax.swing.JButton();
        clearsearch = new javax.swing.JButton();
        addVehiclePanel = new javax.swing.JPanel();
        VmodelF = new javax.swing.JTextField();
        VmakeF = new javax.swing.JTextField();
        VpriceF = new javax.swing.JTextField();
        VyearF = new javax.swing.JTextField();
        VidF = new javax.swing.JTextField();
        VmodelL = new javax.swing.JLabel();
        VmakeL = new javax.swing.JLabel();
        VpriceL = new javax.swing.JLabel();
        VyearL = new javax.swing.JLabel();
        VidL = new javax.swing.JLabel();
        clearVehicle = new javax.swing.JButton();
        addVehicleB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(25, 35, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardealertrydesign/Hopstarter-Sleek-Xp-Basic-Close.24 (1).png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Vehicle Dealerships Management System");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 500, 40));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardealertrydesign/audi.png"))); // NOI18N
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 50, 30));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardealertrydesign/user.png"))); // NOI18N
        jLabel33.setText("ADMIN");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 30, 80, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 60));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("© 2024 DriveMe!.com. All rights reserved. ");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, 10));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardealertrydesign/Hopstarter-Sleek-Xp-Basic-Add.32.png"))); // NOI18N
        jLabel6.setText("ADD VEHICLE");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 110, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("VEHICLE MANAGEMENT");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 190, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("CUSTOMER MANAGEMENT");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        addCustomerMain.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addCustomerMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardealertrydesign/Custom-Icon-Design-Flatastic-4-Male-user-add.32.png"))); // NOI18N
        addCustomerMain.setText("ADD CUSTOMER");
        addCustomerMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCustomerMainMouseClicked(evt);
            }
        });
        jPanel2.add(addCustomerMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardealertrydesign/view (1).png"))); // NOI18N
        jLabel4.setText("VIEW TOTAL CUSTOMERS");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardealertrydesign/icons8-home-40.png"))); // NOI18N
        jLabel8.setText("    HOME");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 130, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("SALES MANAGEMENT");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        recordSales.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        recordSales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardealertrydesign/medical-record.png"))); // NOI18N
        recordSales.setText("RECORD SALES");
        recordSales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recordSalesMouseClicked(evt);
            }
        });
        jPanel2.add(recordSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        viewSalesMain.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        viewSalesMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardealertrydesign/view (1).png"))); // NOI18N
        viewSalesMain.setText("VIEW SALES");
        viewSalesMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewSalesMainMouseClicked(evt);
            }
        });
        jPanel2.add(viewSalesMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 110, -1));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 210, 6));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardealertrydesign/view (1).png"))); // NOI18N
        jLabel31.setText("VIEW AVAILABLE VEHICLES");
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 210, 560));

        MainPanel.setLayout(new java.awt.CardLayout());

        ViewSalesPanel.setBackground(new java.awt.Color(255, 255, 255));

        salesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        salesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salesTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(salesTable);

        searchsaleButton.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        searchsaleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardealertrydesign/magnifying-glass (1).png"))); // NOI18N
        searchsaleButton.setText("SEARCH");
        searchsaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchsaleButtonActionPerformed(evt);
            }
        });

        clearSearch.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        clearSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardealertrydesign/broom (2).png"))); // NOI18N
        clearSearch.setText("CLEAR");
        clearSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearSearchActionPerformed(evt);
            }
        });

        deleteSales.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deleteSales.setText("DELETE");
        deleteSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSalesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ViewSalesPanelLayout = new javax.swing.GroupLayout(ViewSalesPanel);
        ViewSalesPanel.setLayout(ViewSalesPanelLayout);
        ViewSalesPanelLayout.setHorizontalGroup(
            ViewSalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewSalesPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(ViewSalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewSalesPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(ViewSalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salesID)
                            .addComponent(SF1)
                            .addComponent(SF2)
                            .addComponent(SF3)
                            .addComponent(SF4)
                            .addComponent(SF5))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewSalesPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addComponent(deleteSales)
                        .addGap(111, 111, 111))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewSalesPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtsearch3, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(ViewSalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchsaleButton))
                .addGap(425, 425, 425))
        );
        ViewSalesPanelLayout.setVerticalGroup(
            ViewSalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewSalesPanelLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(ViewSalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchsaleButton)
                    .addGroup(ViewSalesPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtsearch3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clearSearch)
                .addGap(27, 27, 27)
                .addGroup(ViewSalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ViewSalesPanelLayout.createSequentialGroup()
                        .addComponent(salesID, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SF1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SF2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SF3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(SF4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SF5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteSales)))
                .addGap(46, 46, 46))
        );

        MainPanel.add(ViewSalesPanel, "card9");

        viewVehiclePanel.setBackground(new java.awt.Color(255, 255, 255));

        vehicleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        vehicleTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vehicleTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(vehicleTable);

        vehicleSearch.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        vehicleSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardealertrydesign/magnifying-glass (1).png"))); // NOI18N
        vehicleSearch.setText("SEARCH");
        vehicleSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleSearchActionPerformed(evt);
            }
        });

        clearSearch2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        clearSearch2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardealertrydesign/broom (2).png"))); // NOI18N
        clearSearch2.setText("CLEAR");
        clearSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearSearch2ActionPerformed(evt);
            }
        });

        updateVehicle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updateVehicle.setText("UPDATE");
        updateVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateVehicleActionPerformed(evt);
            }
        });

        deleteVehicle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deleteVehicle.setText("DELETE");
        deleteVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteVehicleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewVehiclePanelLayout = new javax.swing.GroupLayout(viewVehiclePanel);
        viewVehiclePanel.setLayout(viewVehiclePanelLayout);
        viewVehiclePanelLayout.setHorizontalGroup(
            viewVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewVehiclePanelLayout.createSequentialGroup()
                .addGroup(viewVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewVehiclePanelLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(txtsearch2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(vehicleSearch)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(viewVehiclePanelLayout.createSequentialGroup()
                        .addGroup(viewVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(viewVehiclePanelLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewVehiclePanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clearSearch2)
                                .addGap(221, 221, 221)))
                        .addGroup(viewVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewVehiclePanelLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(viewVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(VF4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(VF5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(VF1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(VF2)
                                    .addComponent(VF3)))
                            .addGroup(viewVehiclePanelLayout.createSequentialGroup()
                                .addComponent(deleteVehicle)
                                .addGap(33, 33, 33)
                                .addComponent(updateVehicle)
                                .addGap(26, 26, 26)))))
                .addGap(36, 36, 36))
        );
        viewVehiclePanelLayout.setVerticalGroup(
            viewVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewVehiclePanelLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(viewVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewVehiclePanelLayout.createSequentialGroup()
                        .addComponent(vehicleSearch)
                        .addGroup(viewVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewVehiclePanelLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(VF1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewVehiclePanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clearSearch2))))
                    .addComponent(txtsearch2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(viewVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewVehiclePanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(VF2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(VF3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(VF4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(VF5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(viewVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteVehicle)
                            .addComponent(updateVehicle)))
                    .addGroup(viewVehiclePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(73, 73, 73))
        );

        MainPanel.add(viewVehiclePanel, "card7");

        SidF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SidFActionPerformed(evt);
            }
        });

        jLabel9.setText("SALE ID:");

        jLabel10.setText("PURCHASE DATE:");

        jLabel11.setText("CUSTOMER ID: ");

        jLabel12.setText("VEHICLE ID: ");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("RECORD SALE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("CLEAR");

        javax.swing.GroupLayout salesRecordLayout = new javax.swing.GroupLayout(salesRecord);
        salesRecord.setLayout(salesRecordLayout);
        salesRecordLayout.setHorizontalGroup(
            salesRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, salesRecordLayout.createSequentialGroup()
                .addGap(92, 341, Short.MAX_VALUE)
                .addGroup(salesRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SvidF, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(salesRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ScidF, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SpurchaseF, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SidF, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(301, 301, 301))
            .addGroup(salesRecordLayout.createSequentialGroup()
                .addGap(408, 408, 408)
                .addComponent(jButton4)
                .addGap(64, 64, 64)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        salesRecordLayout.setVerticalGroup(
            salesRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesRecordLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SidF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SpurchaseF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScidF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SvidF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(salesRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        MainPanel.add(salesRecord, "card6");

        HomePanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("New Car Dealer Partner");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("Join over 350 new car dealer partners  ");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("Become a partner and build your business with DriveMe!");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 153, 153));
        jLabel17.setText("Join the largest automotive network in the Philippines, reaching millions of potential car buyers!  ");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardealertrydesign/mazda.png"))); // NOI18N

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardealertrydesign/jeep.png"))); // NOI18N

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardealertrydesign/chevrolet.png"))); // NOI18N

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardealertrydesign/alfa.png"))); // NOI18N

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardealertrydesign/subaru.png"))); // NOI18N

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardealertrydesign/bmw.png"))); // NOI18N

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardealertrydesign/car.png"))); // NOI18N

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel25.setText("2.7M Visits per Month ");

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardealertrydesign/honda.png"))); // NOI18N

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardealertrydesign/impression.png"))); // NOI18N

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel28.setText("2.7M Visits per Month ");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel29.setText("2.7M Visits per Month ");

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardealertrydesign/cart.png"))); // NOI18N

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomePanelLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel3)))
                    .addGroup(HomePanelLayout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(jLabel18)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel21)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel22)
                        .addGap(78, 78, 78)
                        .addComponent(jLabel23))
                    .addGroup(HomePanelLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)
                        .addGap(74, 74, 74)
                        .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HomePanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel29)
                                .addGap(94, 94, 94)
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel28))
                            .addGroup(HomePanelLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(64, 64, 64)
                                .addComponent(jLabel20)))))
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HomePanelLayout.createSequentialGroup()
                    .addGap(157, 157, 157)
                    .addComponent(jLabel16)
                    .addContainerGap(171, Short.MAX_VALUE)))
            .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HomePanelLayout.createSequentialGroup()
                    .addGap(171, 171, 171)
                    .addComponent(jLabel17)
                    .addContainerGap(190, Short.MAX_VALUE)))
            .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HomePanelLayout.createSequentialGroup()
                    .addGap(206, 206, 206)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(732, Short.MAX_VALUE)))
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePanelLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomePanelLayout.createSequentialGroup()
                        .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HomePanelLayout.createSequentialGroup()
                                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(HomePanelLayout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePanelLayout.createSequentialGroup()
                                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePanelLayout.createSequentialGroup()
                                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(9, 9, 9))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePanelLayout.createSequentialGroup()
                                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10))))))
                            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HomePanelLayout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(jLabel16)
                    .addContainerGap(498, Short.MAX_VALUE)))
            .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HomePanelLayout.createSequentialGroup()
                    .addGap(84, 84, 84)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(466, Short.MAX_VALUE)))
            .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HomePanelLayout.createSequentialGroup()
                    .addGap(224, 224, 224)
                    .addComponent(jLabel19)
                    .addContainerGap(288, Short.MAX_VALUE)))
        );

        MainPanel.add(HomePanel, "card4");

        CphoneF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CphoneFActionPerformed(evt);
            }
        });

        CemailF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CemailFActionPerformed(evt);
            }
        });

        CnameL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CnameL.setText("NAME: ");

        CemailL.setText("EMAIL:");

        CphoneL.setText("PHONE NUMBER: ");

        CaddressL.setText("ADDRESS: ");

        CidL.setText("CUSTOMER ID:");

        ClearCustomer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ClearCustomer.setText("CLEAR");
        ClearCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearCustomerActionPerformed(evt);
            }
        });

        addCustomerB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addCustomerB.setText("ADD CUSTOMER");
        addCustomerB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addCustomerPanelLayout = new javax.swing.GroupLayout(addCustomerPanel);
        addCustomerPanel.setLayout(addCustomerPanelLayout);
        addCustomerPanelLayout.setHorizontalGroup(
            addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCustomerPanelLayout.createSequentialGroup()
                .addGap(394, 394, 394)
                .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CnameL, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CphoneL, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CphoneF, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CnameF, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CidL, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CaddressF, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                            .addComponent(CaddressL, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CidF))
                        .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CemailL, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CemailF, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(addCustomerPanelLayout.createSequentialGroup()
                .addGap(443, 443, 443)
                .addComponent(ClearCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(addCustomerB)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        addCustomerPanelLayout.setVerticalGroup(
            addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCustomerPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(CnameL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CnameF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(CemailL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CemailF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CphoneL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CphoneF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CaddressL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CaddressF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(CidL)
                .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addCustomerPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CidF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addCustomerPanelLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(addCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addCustomerB)
                            .addComponent(ClearCustomer))))
                .addGap(140, 140, 140))
        );

        MainPanel.add(addCustomerPanel, "card3");

        viewCustomers.setBackground(new java.awt.Color(255, 255, 255));

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        customerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(customerTable);

        searchCbutton.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        searchCbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardealertrydesign/magnifying-glass (1).png"))); // NOI18N
        searchCbutton.setText("SEARCH");
        searchCbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCbuttonActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        customerUpdateB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        customerUpdateB.setText("UPDATE");
        customerUpdateB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerUpdateBActionPerformed(evt);
            }
        });

        clearsearch.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        clearsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardealertrydesign/broom (2).png"))); // NOI18N
        clearsearch.setText("CLEAR");
        clearsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearsearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewCustomersLayout = new javax.swing.GroupLayout(viewCustomers);
        viewCustomers.setLayout(viewCustomersLayout);
        viewCustomersLayout.setHorizontalGroup(
            viewCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewCustomersLayout.createSequentialGroup()
                .addGroup(viewCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewCustomersLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewCustomersLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addGroup(viewCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(clearsearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchCbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(viewCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(viewCustomersLayout.createSequentialGroup()
                        .addGroup(viewCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CF8)
                            .addComponent(CF7)
                            .addComponent(CF9)
                            .addComponent(CF10)
                            .addComponent(customerID, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewCustomersLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(customerUpdateB)
                        .addGap(82, 82, 82))))
        );
        viewCustomersLayout.setVerticalGroup(
            viewCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewCustomersLayout.createSequentialGroup()
                .addGroup(viewCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewCustomersLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(CF7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CF8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewCustomersLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(viewCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchCbutton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearsearch)))
                .addGroup(viewCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewCustomersLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewCustomersLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(CF9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(CF10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(customerID, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(viewCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(customerUpdateB))))
                .addGap(47, 47, 47))
        );

        MainPanel.add(viewCustomers, "card2");

        VmodelL.setText("VEHICLE MODEL:");

        VmakeL.setText("VEHICLE MAKE:");

        VpriceL.setText("VEHICLE PRICE:");

        VyearL.setText("VEHICLE YEAR MODEL: ");

        VidL.setText("VEHICLE ID: ");

        clearVehicle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        clearVehicle.setText("CLEAR");
        clearVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearVehicleActionPerformed(evt);
            }
        });

        addVehicleB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addVehicleB.setText("ADD VEHICLE");
        addVehicleB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVehicleBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addVehiclePanelLayout = new javax.swing.GroupLayout(addVehiclePanel);
        addVehiclePanel.setLayout(addVehiclePanelLayout);
        addVehiclePanelLayout.setHorizontalGroup(
            addVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addVehiclePanelLayout.createSequentialGroup()
                .addGap(456, 456, 456)
                .addComponent(clearVehicle)
                .addGap(29, 29, 29)
                .addComponent(addVehicleB)
                .addContainerGap(342, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addVehiclePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(addVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VmodelL, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VmakeL, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VpriceL, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VyearL, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VidL, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VidF, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VyearF, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VpriceF, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VmakeF, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VmodelF, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(286, 286, 286))
        );
        addVehiclePanelLayout.setVerticalGroup(
            addVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addVehiclePanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(VmodelL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VmodelF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(VmakeL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VmakeF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(VpriceL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VpriceF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(VyearL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VyearF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(VidL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VidF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(addVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearVehicle)
                    .addComponent(addVehicleB))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        MainPanel.add(addVehiclePanel, "card5");

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 1010, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        int result = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit? ", "CONFIRMATION",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(result == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    
    private void clearButton(){
        CnameF.setText("");
        CphoneF.setText("");
        CemailF.setText("");
        CaddressF.setText("");
        CidF.setText("");
        
        VmakeF.setText("");
        VmodelF.setText("");
        VidF.setText("");
        VpriceF.setText("");
        VyearF.setText("");
        
        CF7.setText("");
        CF8.setText("");
        CF9.setText("");
        CF10.setText("");
        customerID.setText("");
        
        VF1.setText("");
        VF2.setText("");
        VF3.setText("");
        VF4.setText("");
        VF5.setText("");
        
        SidF.setText("");
        SpurchaseF.setText("");
        ScidF.setText("");
        SvidF.setText("");
        
        }
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        MainPanel.removeAll();
        MainPanel.add(HomePanel);
        
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void CemailFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CemailFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CemailFActionPerformed

    private void CphoneFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CphoneFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CphoneFActionPerformed

    private void addCustomerMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCustomerMainMouseClicked
        // TODO add your handling code here:
        MainPanel.removeAll();
        MainPanel.add(addCustomerPanel);
        
        MainPanel.repaint();
        MainPanel.revalidate();
               
    }//GEN-LAST:event_addCustomerMainMouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        MainPanel.removeAll();
        MainPanel.add(addVehiclePanel);
        
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        MainPanel.removeAll();
        MainPanel.add(viewCustomers);
        
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void ClearCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearCustomerActionPerformed
        // TODO add your handling code here:
        clearButton();
    }//GEN-LAST:event_ClearCustomerActionPerformed

    private void addCustomerBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerBActionPerformed
          try {
        String Vmake = VmakeF.getText() == null ? "" : VmakeF.getText().trim();
        String Vmodel = VmodelF.getText() == null ? "" : VmodelF.getText().trim();
        String Vid = VidF.getText() == null ? "" : VidF.getText().trim();
        String Vyear = VyearF.getText() == null ? "" : VyearF.getText().trim();
        
        // Handle price field specifically
        double Vprice = 0.0; // Default to 0.0 if blank
        try {
            // Only try to parse price if the field is not empty
            if (!VpriceF.getText().trim().isEmpty()) {
                Vprice = Double.parseDouble(VpriceF.getText().trim());
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, 
                "Invalid price format. Please enter a valid number.", 
                "Price Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        vehicleManagement Vehicle = new vehicleManagement(Vmake, Vmodel, Vid, Vprice, Vyear);
        Vehicle.addVehicle();
        clearButton();
        Vehicle.fillTableVehicle(vehicleTable); 

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, 
            "Failed to add vehicle: " + e.getMessage(), 
            "ERROR", 
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_addCustomerBActionPerformed

    private void searchCbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCbuttonActionPerformed
        // TODO add your handling code here:
        Customer.searchCustomer(customerTable, txtsearch);
    }//GEN-LAST:event_searchCbuttonActionPerformed

    private void addVehicleBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVehicleBActionPerformed
        // TODO add your handling code here:
         try {
            String Vmake = VmakeF.getText();
            String Vmodel = VmodelF.getText();
            double Vprice = Double.parseDouble(VpriceF.getText());
            String Vid = VidF.getText();
            String Vyear = VyearF.getText();


            vehicleManagement Vehicle = new vehicleManagement(Vmake, Vmodel, Vid, Vprice, Vyear );
            Vehicle.addVehicle();
            clearButton();
            Vehicle.fillTableVehicle(vehicleTable); 

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "may mali ditro " , "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addVehicleBActionPerformed

    private void clearVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearVehicleActionPerformed
        // TODO add your handling code here:
        clearButton();
    }//GEN-LAST:event_clearVehicleActionPerformed

    private void vehicleSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleSearchActionPerformed
        // TODO add your handling code here:
        vehicleManagement Vehicle = new vehicleManagement("", "", "", 0.0, null);
        Vehicle.searchVehicle(vehicleTable, txtsearch2); 
    }//GEN-LAST:event_vehicleSearchActionPerformed

    private void customerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerTableMouseClicked
        // TODO add your handling code here:
        DBmanager db = new DBmanager();
        Connection con = db.getConnection();
        int noOfRow = customerTable.getSelectedRow();
        if (noOfRow == -1) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table.", "No Row Selected", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String click = customerTable.getModel().getValueAt(noOfRow, 0).toString();
        if (click == null || click.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Invalid.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try (PreparedStatement ps = con.prepareStatement("SELECT * FROM tblcustomer WHERE CustomerName = ?")) {
            ps.setString(1, click);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    CF7.setText(rs.getString("CustomerName"));
                    CF8.setText(rs.getString("CustomerEmail"));
                    CF9.setText(rs.getString("CustomerPhone"));
                    CF10.setText(rs.getString("CustomerAddress"));
                    customerID.setText(rs.getString("CustomerId"));
                } else {
                    JOptionPane.showMessageDialog(null, "Information not found", "Try Again", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "An error occurred while retrieving customer information. Please try again.", "Database Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();  // Optionally log the stack trace for debugging
        }
    }//GEN-LAST:event_customerTableMouseClicked

    private void customerUpdateBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerUpdateBActionPerformed
        // TODO add your handling code here:
         Update update = new Update();
         update.updateCustomer(CF7, CF8, CF9, CF10, customerID);
         Customer.fillTableCustomer(customerTable);
         clearButton();
    }//GEN-LAST:event_customerUpdateBActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        MainPanel.removeAll();
        MainPanel.add(viewVehiclePanel);
        
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void deleteVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteVehicleActionPerformed
        // TODO add your handling code here:
        Delete delete = new Delete();
        delete.deleteVehicle(VF5);
        Vehicle.fillTableVehicle(vehicleTable);
        

    }//GEN-LAST:event_deleteVehicleActionPerformed

    private void clearSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearSearch2ActionPerformed
        // TODO add your handling code here:
        txtsearch2.setText("");
        Vehicle.fillTableVehicle(vehicleTable);
        
        VF1.setText("");
        VF2.setText("");
        VF3.setText("");
        VF4.setText("");
        VF5.setText("");
        
        
    }//GEN-LAST:event_clearSearch2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         
        Delete delete = new Delete();
        delete.deleteCustomer(customerID);
        Customer.fillTableCustomer(customerTable);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void SidFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SidFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SidFActionPerformed

    private void clearsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearsearchActionPerformed

        txtsearch.setText("");
        customerManagement Customer = new customerManagement("", "", "", "", "");
        Customer.fillTableCustomer(customerTable);
        
        CF7.setText("");
        CF8.setText("");
        CF9.setText("");
        CF10.setText("");
        customerID.setText("");
    }//GEN-LAST:event_clearsearchActionPerformed

    private void vehicleTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vehicleTableMouseClicked
        // TODO add your handling code here:
        DBmanager db = new DBmanager();
        Connection con = db.getConnection();
        int noOfRow = vehicleTable.getSelectedRow();
        if (noOfRow == -1) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table.", "No Row Selected", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String click = vehicleTable.getModel().getValueAt(noOfRow, 0).toString();
        if (click == null || click.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Invalid.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try (PreparedStatement ps = con.prepareStatement("SELECT * FROM tblvehicle WHERE VehicleMake = ?")) {
            ps.setString(1, click);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    VF1.setText(rs.getString("VehicleMake"));
                    VF2.setText(rs.getString("VehicleModel"));
                    VF3.setText(rs.getString("VehiclePrice"));
                    VF4.setText(rs.getString("VehicleYear"));
                    VF5.setText(rs.getString("VehicleId"));
                } else {
                    JOptionPane.showMessageDialog(null, "Information not found", "Try Again", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "An error occurred while retrieving customer information. Please try again.", "Database Error", JOptionPane.ERROR_MESSAGE);
        }
                       
    }//GEN-LAST:event_vehicleTableMouseClicked

    private void updateVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateVehicleActionPerformed
        // TODO add your handling code here:
        Update update = new Update();
        update.updateVehicle(VF1, VF2, VF3, VF4, VF5);
        Vehicle.fillTableVehicle(vehicleTable);
         clearButton(); 
    }//GEN-LAST:event_updateVehicleActionPerformed

    private void recordSalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recordSalesMouseClicked
        // TODO add your handling code here:
        MainPanel.removeAll();
        MainPanel.add(salesRecord);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_recordSalesMouseClicked

    private void viewSalesMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewSalesMainMouseClicked
        // TODO add your handling code here:
        MainPanel.removeAll();
        MainPanel.add(ViewSalesPanel);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_viewSalesMainMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
           try {
       
    String SsalesId = SidF.getText();
    String Syear = SpurchaseF.getText();
    String Scid = ScidF.getText();
    String Svid = SvidF.getText();
    
    if (!SsalesId.isEmpty() && !Syear.isEmpty() && !Scid.isEmpty() && !Svid.isEmpty()) {

        customerManagement Customer = new customerManagement("", "", "", "", Scid);
        vehicleManagement Vehicle = new vehicleManagement("", "", Svid, 0, "");
        String[] customerDetails = Customer.getCustomerDetailsById(Scid);
        String[] vehicleDetails = Vehicle.getVehicleDetailsById(Svid);
        String customerName = customerDetails[0]; 
        String vehicleMake = vehicleDetails[0];
        String vehicleModel = vehicleDetails[1];
        String vehiclePrice = vehicleDetails[2]; 

        salesManagement sale = new salesManagement(SsalesId, Syear, Customer, Vehicle);
        sale.processSale();
        JOptionPane.showMessageDialog(null, "Sale processed successfully!");
        sale.fillTableSales(salesTable);
        clearButton();
    } else {
        JOptionPane.showMessageDialog(null, "Fill in all fields", "ERROR", JOptionPane.ERROR_MESSAGE);
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "An error occurred: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void searchsaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchsaleButtonActionPerformed
        // TODO add your handling code here:
        Sales.searchSales(salesTable, txtsearch3);
        
        
    }//GEN-LAST:event_searchsaleButtonActionPerformed

    private void clearSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearSearchActionPerformed
        // TODO add your handling code here:
        txtsearch3.setText("");
        Sales.fillTableSales(salesTable);
        salesID.setText("");
        SF1.setText("");
        SF2.setText("");
        SF3.setText("");
        SF4.setText("");
        SF5.setText("");
        
        
    }//GEN-LAST:event_clearSearchActionPerformed

    private void deleteSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSalesActionPerformed
        // TODO add your handling code here:
        Delete delete = new Delete();
        delete.deleteSales(salesID);
        Sales.fillTableSales(salesTable);
    }//GEN-LAST:event_deleteSalesActionPerformed

    private void salesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesTableMouseClicked
        // TODO add your handling code here:
        DBmanager db = new DBmanager();
        Connection con = db.getConnection();
        int noOfRow = salesTable.getSelectedRow();
        if (noOfRow == -1) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table.", "No Row Selected", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String click = salesTable.getModel().getValueAt(noOfRow, 0).toString();
        if (click == null || click.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Invalid.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try (PreparedStatement ps = con.prepareStatement("SELECT * FROM tblsales WHERE SaleID = ?")) {
            ps.setString(1, click);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                salesID.setText(rs.getString("SaleID"));
                SF1.setText(rs.getString("YearSale"));
                SF2.setText(("CustomerName"));  
                SF3.setText( rs.getString("VehicleMake"));
                SF4.setText(rs.getString("VehicleModel"));
                SF5.setText(rs.getString("VehiclePrice"));
                } else {
                    JOptionPane.showMessageDialog(null, "Information not found", "Try Again", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "An error occurred while retrieving customer information. Please try again.", "Database Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(); 
        }
    }//GEN-LAST:event_salesTableMouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        // TODO add your handling code here:
        MainPanel.removeAll();
        MainPanel.add(viewVehiclePanel);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_jLabel31MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CF10;
    private javax.swing.JTextField CF7;
    private javax.swing.JTextField CF8;
    private javax.swing.JTextField CF9;
    private javax.swing.JTextField CaddressF;
    private javax.swing.JLabel CaddressL;
    private javax.swing.JTextField CemailF;
    private javax.swing.JLabel CemailL;
    private javax.swing.JTextField CidF;
    private javax.swing.JLabel CidL;
    private javax.swing.JButton ClearCustomer;
    private javax.swing.JTextField CnameF;
    private javax.swing.JLabel CnameL;
    private javax.swing.JTextField CphoneF;
    private javax.swing.JLabel CphoneL;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JTextField SF1;
    private javax.swing.JTextField SF2;
    private javax.swing.JTextField SF3;
    private javax.swing.JTextField SF4;
    private javax.swing.JTextField SF5;
    private javax.swing.JTextField ScidF;
    private javax.swing.JTextField SidF;
    private javax.swing.JTextField SpurchaseF;
    private javax.swing.JTextField SvidF;
    private javax.swing.JTextField VF1;
    private javax.swing.JTextField VF2;
    private javax.swing.JTextField VF3;
    private javax.swing.JTextField VF4;
    private javax.swing.JTextField VF5;
    private javax.swing.JTextField VidF;
    private javax.swing.JLabel VidL;
    private javax.swing.JPanel ViewSalesPanel;
    private javax.swing.JTextField VmakeF;
    private javax.swing.JLabel VmakeL;
    private javax.swing.JTextField VmodelF;
    private javax.swing.JLabel VmodelL;
    private javax.swing.JTextField VpriceF;
    private javax.swing.JLabel VpriceL;
    private javax.swing.JTextField VyearF;
    private javax.swing.JLabel VyearL;
    private javax.swing.JButton addCustomerB;
    private javax.swing.JLabel addCustomerMain;
    private javax.swing.JPanel addCustomerPanel;
    private javax.swing.JButton addVehicleB;
    private javax.swing.JPanel addVehiclePanel;
    private javax.swing.JButton clearSearch;
    private javax.swing.JButton clearSearch2;
    private javax.swing.JButton clearVehicle;
    private javax.swing.JButton clearsearch;
    private javax.swing.JTextField customerID;
    private javax.swing.JTable customerTable;
    private javax.swing.JButton customerUpdateB;
    private javax.swing.JButton deleteSales;
    private javax.swing.JButton deleteVehicle;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel recordSales;
    private javax.swing.JTextField salesID;
    private javax.swing.JPanel salesRecord;
    private javax.swing.JTable salesTable;
    private javax.swing.JButton searchCbutton;
    private javax.swing.JButton searchsaleButton;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txtsearch2;
    private javax.swing.JTextField txtsearch3;
    private javax.swing.JButton updateVehicle;
    private javax.swing.JButton vehicleSearch;
    private javax.swing.JTable vehicleTable;
    private javax.swing.JPanel viewCustomers;
    private javax.swing.JLabel viewSalesMain;
    private javax.swing.JPanel viewVehiclePanel;
    // End of variables declaration//GEN-END:variables
}
