/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cardealertrydesign;

import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Jericho Mico
 */

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
   private DBmanager dbManager;
   public Login() {
    setTitle("Login Window");
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    setSize(400, 300);
    setUndecorated(true);
    initComponents();           // Initializes all buttons/labels/etc
    setLocationRelativeTo(null); // THEN center the frame
    dbManager = new DBmanager();
}
public class DBmanager {
    private Connection con;
        
    public DBmanager() {
        try {
            String url = "jdbc:mysql://localhost:3306/dbcardealership"; 
            String user = "root"; 
            String password = ""; 
            con = DriverManager.getConnection(url, user, password);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, 
                "Failed to connect to database: " + e.getMessage(), 
                "Database Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public Connection getConnection() {
        return con;
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Admin_log = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Admin_pas = new javax.swing.JTextField();
        admin_login = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Customer_pass = new javax.swing.JTextField();
        customer_login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(25, 35, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardealertrydesign/Hopstarter-Sleek-Xp-Basic-Close.24 (1).png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 30, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Vehicle Dealerships Management System");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 500, 40));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardealertrydesign/audi.png"))); // NOI18N
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 50, 30));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("ADMIN ID PASSWORD");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 220, 20));

        Admin_log.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Admin_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_logActionPerformed(evt);
            }
        });
        jPanel3.add(Admin_log, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 200, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("ADMIN LOGIN");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 160, 20));

        Admin_pas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Admin_pas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_pasActionPerformed(evt);
            }
        });
        jPanel3.add(Admin_pas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 200, 30));

        admin_login.setText("Login");
        admin_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admin_loginMouseClicked(evt);
            }
        });
        admin_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_loginActionPerformed(evt);
            }
        });
        jPanel3.add(admin_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("USER LOGIN");

        Customer_pass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Customer_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customer_passActionPerformed(evt);
            }
        });

        customer_login.setText("Login");
        customer_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customer_loginMouseClicked(evt);
            }
        });
        customer_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(217, 217, 217)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Customer_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(279, 279, 279)
                                .addComponent(customer_login))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Customer_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(customer_login)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
    int result = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit? ", "CONFIRMATION",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(result == JOptionPane.YES_OPTION){
            System.exit(0);
        }  
    }//GEN-LAST:event_jLabel1MouseClicked

    private void Admin_pasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_pasActionPerformed
    Admin_pasActionPerformed(null);
    }//GEN-LAST:event_Admin_pasActionPerformed

    private void Admin_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_logActionPerformed
        
    }//GEN-LAST:event_Admin_logActionPerformed

    private void Customer_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customer_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Customer_passActionPerformed

    private void admin_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_loginActionPerformed
        try {
        String username = Admin_log.getText();
        String password = Admin_pas.getText();
        
        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Please enter both username and password", 
                "Login Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        DBmanager dbManager = new DBmanager();
        Connection conn = dbManager.getConnection();
        String query = "SELECT * FROM tbllogin WHERE Admin_Name = ? AND Admin_ID_pass = ?";
        PreparedStatement ps = conn.prepareStatement(query);
        ps.setString(1, username);
        ps.setString(2, password);
        
        ResultSet rs = ps.executeQuery();
        
        if (rs.next()) {
            // Admin exists, login successful
            JOptionPane.showMessageDialog(this, 
                "Login successful!", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);
            
            // Open the main application
            CarJframe mainFrame = new CarJframe();
            mainFrame.setVisible(true);
            this.dispose(); // Close the login window
            
        } else {
            // Invalid credentials
            JOptionPane.showMessageDialog(this, 
                "Invalid username or password", 
                "Login Failed", 
                JOptionPane.ERROR_MESSAGE);
        }
        
        rs.close();
        ps.close();
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Error during login: " + e.getMessage(), 
            "Database Error", 
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_admin_loginActionPerformed

    private void admin_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_loginMouseClicked
         admin_loginActionPerformed(null);
    }//GEN-LAST:event_admin_loginMouseClicked

    private void customer_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customer_loginMouseClicked
         customer_loginActionPerformed(null);
    }//GEN-LAST:event_customer_loginMouseClicked

    private void customer_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_loginActionPerformed
        try {
        String customerId = Customer_pass.getText();
        
        if (customerId.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Please enter your user ID", 
                "Login Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        DBmanager dbManager = new DBmanager();
        Connection conn = dbManager.getConnection();
        String query = "SELECT * FROM tbluser WHERE User_Id = ?";
        PreparedStatement ps = conn.prepareStatement(query);
        ps.setString(1, customerId);
        
        ResultSet rs = ps.executeQuery();
        
        if (rs.next()) {
            // Customer exists, login successful
            JOptionPane.showMessageDialog(this, 
                "Login successful!", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);
            
            // Open the main application
            User mainFrame = new User();
            mainFrame.setVisible(true);
//            CarJframe mainFrame = new CarJframe();  view yug cars tas add narin
//            mainFrame.setVisible(true);
            this.dispose(); // Close the login window
            
        } else {
            // Invalid customer ID
            JOptionPane.showMessageDialog(this, 
                "Invalid user ID", 
                "Login Failed", 
                JOptionPane.ERROR_MESSAGE);
        }
        
        rs.close();
        ps.close();
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Error during login: " + e.getMessage(), 
            "Database Error", 
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_customer_loginActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Admin_log;
    private javax.swing.JTextField Admin_pas;
    private javax.swing.JTextField Customer_pass;
    private javax.swing.JButton admin_login;
    private javax.swing.JButton customer_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
